# Site settings
author: Brad Schrag
title: Brad Schrag Learns
header-img: img/home-bg.png
email: brad.schrag@gmail.com
copyright_name: Brad Schrag
description: > # this means to ignore newlines until "baseurl:"
  Simple space to talk about coding projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bschrag620

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
